import React from 'react';
import Head from 'next/head';
import Main from '../components/Main'


export default function Home() {
  return (
    <>
      <Head>
        <title>ConsciousDAO</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="Assets/favicon.png" />
      </Head>

     <Main />



     
      
      
      {/* Header */}
      {/* Logo (Type/Graphic)*/}
      {/* Paragraph Card*/}
      {/* Discord Button*/}
    </>      
  )
}
